### ISSUE TITLE
Job doesn't source ~/.Renvion file

### ISSUE THREAD

**Issue by johrstrom** [OSC/bc_example_rstudio#2]
Apparently the `~/.Renvion` is an R specific file that has exports and environment variables that the R language runtimes can use. Things like `R_LIBS_USER` can listed there and picked up.

These scripts do not source that file, yet they do look for env variables like [R_LIBS_USER](https://github.com/OSC/bc_example_rstudio/blob/a44541f75ddedb07914dfc562795c6c5be956439/template/script.sh.erb#L36).  

These could be exports in a users `~/.bashrc`, but As indicated by this [discourse topic](https://discourse.osc.edu/t/bc-example-rstudio-problem-question/533) R users expect `~/.Renviron` file to be sourced in both R command line runtimes and RStudio.

**Comment by ericfranz** [comment]
Based on [this comment](https://discourse.osc.edu/t/bc-example-rstudio-problem-question/533/6) it would seem that RStudio does in fact source these files, and we do not need to add any special code to fix this. @johrstrom if you have no objections lets mark this as invalid and close it.

**Comment by johrstrom** [comment]
Yea actually rereading the initial comment he says `When they start up an Rstudio session, the R_LIBS_USER variable does show as set when checking with Sys.getenv() (complete with proper version replacing the ‘%v’ variable), but does not show up when checking .libPaths().`

But we do have [this line](https://github.com/OSC/bc_example_rstudio/blob/a44541f75ddedb07914dfc562795c6c5be956439/template/script.sh.erb#L36) that will never be populated unless they add to their bashrc and it's only going to cause more confusion.
